repos:
-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
    -   id: bandit
        args: [--recursive]
        exclude: ^tests/
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: [--line-length=79]
        additional_dependencies: [click==8.2.1]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
